### PR TITLE
Add more configuration options

### PR DESCRIPTION
**Pull request by istudyatuni**
- Add settings to configure time format for filenames and "date" property
- Add setting to configure start of next day

Also:

- Added "dayjs" dependency. It's pretty small (comparing to moment.js)
- Enabled "minify" option of esbuild when building for prod

### CODE REVIEW

**Comment by dominikmayer** [comment]
Hi @istudyatuni, thank you very much for this pull request. I'll try to review it in the next days.

Allowing the user to configure the start of the day has been on my to do list.

Regarding the time format: I don't mind giving users the option to change it. But for this one I think we should create a button to reset to the default and maybe also add cautious language. Two reasons:

1. If you change it to something like DD-MM-YYYY suddenly all your entries show up in the wrong order in the sidebar and in your file manager and it will be hard to find the entry you're looking for. (Creation date as a sort option only works if you don't create past entries, which is a common use case for adding media entries.)
2. These options – especially the frontmatter one – will not work with the upcoming Yesterday app which, among other things, lets you add entries from images. So users that might want to use the app need to have the entries in the current format or the entries won't show up.

**Comment by istudyatuni** [comment]
Yeah, after thinking about it more, I think it's a bad idea to configure filename.

About the frontmatter - I'm not quite sure what you mean. Will the "date" value affect app? I thought it just something visual and easier to read because it can be manually edited, so the problem would remain regardless of the configured format - if someone edits the "date" and it affect the entry display, the entry won't display

**Comment by dominikmayer** [comment]
The app will read the date from the frontmatter and it expects a specific format. If it cannot parse the date field it will not show the entry at all as it wouldn't know where to put it in respect to other entries. We can't fallback to the file name either because it lacks the timezone information.

You're right about manual edits. The app won't show the frontmatter though. So the user would edit the time in the app. If a user messes with the fronmatter in a text editor then the entry wouldn't be shown. I don't expect this to be too big of an issue though.

**Comment by istudyatuni** [comment]
Okay, possible solutions I see:

1. Show a warning to user, when he wants to edit this field
2. Add a warning to README or something, that 'date' will affect app (but probably many people won't see this)
3. Use another field. My initial usecase - I want to see the weekday
4. Use configured format, then the default format for parsing date in the app (because manual edits still here)

I don't understand, how app will work: like obsidian, on top of plain files, or obsidian data will be imported in the app?

About not showing entries with incorrect "date" in the app - probably a bad idea, and it's better to rely on the filename, and timezone can be selected from the system. This would also help with manual edits.

About manual editing - as I know, it is generally better not to expect something from users, because if there is a possibility to edit this field - it will be edited with high probability.

> If it cannot parse the date field it will not show the entry at all as it wouldn't know where to put it in respect to other entries

I think getting the filename is enough to determine the position next to other records, timezone is not needed

**Comment by dominikmayer** [comment]
> I don't understand, how app will work: like obsidian, on top of plain files, or obsidian data will be imported in the app?

On plain text files. You will be able to edit the journal in Obsidian and in the app in parallel, which is what I've been doing for a long time now.

> About not showing entries with incorrect "date" in the app - probably a bad idea, and it's better to rely on the filename, and timezone can be selected from the system. This would also help with manual edits.

This only works if all entries are created in the same timezone. For anyone that has been traveling to other time zones or is living in a country with summer and winter time this will completely mess up entry display.

> About manual editing - as I know, it is generally better not to expect something from users, because if there is a possibility to edit this field - it will be edited with high probability.

For app users the only way for them to edit the field is to open the entry in a text editor. It's a manageable risk, I'd say.

**Comment by istudyatuni** [comment]
Could you also comment on a possible solution? So that I can end this journey :grin: 

> For app users the only way for them to edit the field is to open the entry in a text editor. It's a manageable risk, I'd say

Yeah, but app is not released, so until then I think it's not (looking at number of downloads)

**Comment by dominikmayer** [comment]
> Could you also comment on a possible solution? So that I can end this journey 😁

I'm still in the middle of something and haven't had time to look at the commits. Sorry for that. Will probably get to it towards the middle of the week.

As I said above: I don't mind having anything edited. There should just be a button to reset to the defaults for anything date related.

**Comment by dominikmayer** [comment]
Okay, I checked. Works well. Two issues still remain:

- [ ] When a user deletes the content of the format string then the plugin should revert to the default format (I get something like "2024-05-10T15:56:51+07:00" instead).
- [ ] The reset button for the frontmatter time format is still missing. (With above issue fixed it could just remove the custom formatting, maybe using the default one as a placeholder for the text field).

Could you address them?

**Comment by istudyatuni** [comment]
Yes, but a bit later

**Comment by istudyatuni** [comment]
I can add the reset button, but I don't know to make it to reset value in the input field immediately. Code looks like

```ts
.addExtraButton(b => b
    .setIcon('reset')
    .onClick(async () => {
        this.plugin.settings.datePropFormat = DEFAULT_SETTINGS.datePropFormat;
        await this.plugin.saveSettings();
    }))
.addMomentFormat(// ...
```

**Comment by dominikmayer** [comment]
I looked at how the [Obsidian Minimal Settings Plugin](https://github.com/kepano/obsidian-minimal-settings/blob/main/main.ts) solves this and used their way. Please review. If this is okay I guess we can merge.

**Comment by istudyatuni** [comment]
Looks fine, thanks!

**Pull request merged**
